[#296] Fix SyntaxError for beautifulsoup4==4.7.0
beautifulsoup4==4.7.0 uses soupsieve as its new CSS selector
https://github.com/facelessuser/soupsieve

Which is NOT allowed css selector starts with '>' anymore.
If we don't modify it, we will get the error below:

```
File "/home/m157q/.virtualenvs/zdict-MhZkMH0u/lib/python3.6/site-packages/soupsieve/css_parser.py",
line 566, in parse_split
    raise SyntaxError("Cannot start or end selector with
'{}'".format(m.group('relation')))
  File "<string>", line None
SyntaxError: Cannot start or end selector with '>'
```